server:
  port: 8082

spring:
  application:
    name: competitor-simulator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pricing}
    username: ${SPRING_DATASOURCE_USERNAME:pricing}
    password: ${SPRING_DATASOURCE_PASSWORD:pricing}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
