apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pricing
resources:
  - namespace.yaml
  - configmap.yaml
  - pricing-api.yaml
  - price-engine.yaml
  - competitor-simulator.yaml
  - web.yaml
